# Generated by Django 4.1.1 on 2023-01-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prclient',
            fields=[
                ('clientid', models.AutoField(db_column='clientID', primary_key=True, serialize=False)),
                ('clemail', models.CharField(db_column='CLemail', max_length=50)),
                ('clpassword', models.CharField(db_column='CLpassword', max_length=50)),
                ('clcompany_name', models.CharField(db_column='CLcompany_name', max_length=50)),
                ('clphone_number', models.CharField(db_column='CLphone_number', max_length=50)),
                ('cluniqueid', models.CharField(db_column='CLuniqueId', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'prclient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrclientAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('client_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_api.prclient')),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
